# write docker compose file

version: '3.0'
services:
  server:
    build: .
    ports:
      - "1234:1234"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    stdin_open: true
    tty: true
    command: yarn dev
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
volumes:
  node_modules: